# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'Unsinkable' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Unsinkable
  # add the Firebase pod for Google Analytics
  
  #Add version
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'Kingfisher'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  target 'UnsinkableTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnsinkableUITests' do
    # Pods for testing
  end

end
